// Common Jira/Slack emoji shortnames mapped to their unicode characters
export const EMOJI_MAP: Record<string, string> = {
  // Checks & status
  check_mark: "✅",
  white_check_mark: "✅",
  "+1": "👍",
  "-1": "👎",
  heavy_check_mark: "✔️",
  x: "❌",
  cross_mark: "❌",
  heavy_multiplication_x: "✖️",
  no_entry: "⛔",
  no_entry_sign: "🚫",
  warning: "⚠️",
  exclamation: "❗",
  heavy_exclamation_mark: "❗",
  grey_exclamation: "❕",
  question_mark: "❓",
  question: "❓",
  grey_question: "❔",
  // Info & communication
  info: "ℹ️",
  information_source: "ℹ️",
  loudspeaker: "📢",
  mega: "📣",
  speech_balloon: "💬",
  thought_balloon: "💭",
  // Faces & people
  slightly_smiling_face: "🙂",
  smile: "😊",
  smiley: "😃",
  grinning: "😀",
  wink: "😉",
  blush: "😊",
  laughing: "😆",
  sweat_smile: "😅",
  joy: "😂",
  rofl: "🤣",
  thinking: "🤔",
  thinking_face: "🤔",
  neutral_face: "😐",
  expressionless: "😑",
  unamused: "😒",
  rolling_eyes: "🙄",
  stuck_out_tongue: "😛",
  stuck_out_tongue_winking_eye: "😜",
  stuck_out_tongue_closed_eyes: "😝",
  yum: "😋",
  sunglasses: "😎",
  sweat: "😓",
  disappointed: "😞",
  worried: "😟",
  cry: "😢",
  sob: "😭",
  fearful: "😨",
  scream: "😱",
  flushed: "😳",
  pensive: "😔",
  confounded: "😖",
  rage: "😡",
  angry: "😠",
  sleeping: "😴",
  mask: "😷",
  nerd_face: "🤓",
  robot_face: "🤖",
  ghost: "👻",
  skull: "💀",
  // Hands & gestures
  thumbsup: "👍",
  thumbsdown: "👎",
  ok_hand: "👌",
  wave: "👋",
  raised_hand: "✋",
  clap: "👏",
  pray: "🙏",
  muscle: "💪",
  point_right: "👉",
  point_left: "👈",
  point_up: "☝️",
  point_up_2: "👆",
  point_down: "👇",
  crossed_fingers: "🤞",
  v: "✌️",
  metal: "🤘",
  writing_hand: "✍️",
  // Objects & tools
  star: "⭐",
  star2: "🌟",
  sparkles: "✨",
  heart: "❤️",
  orange_heart: "🧡",
  yellow_heart: "💛",
  green_heart: "💚",
  blue_heart: "💙",
  purple_heart: "💜",
  black_heart: "🖤",
  fire: "🔥",
  rocket: "🚀",
  tada: "🎉",
  gift: "🎁",
  trophy: "🏆",
  medal: "🏅",
  100: "💯",
  memo: "📝",
  pencil: "✏️",
  pencil2: "✏️",
  bug: "🐛",
  wrench: "🔧",
  hammer: "🔨",
  hammer_and_wrench: "🛠️",
  bulb: "💡",
  zap: "⚡",
  eyes: "👀",
  eye: "👁️",
  microscope: "🔬",
  telescope: "🔭",
  computer: "💻",
  desktop_computer: "🖥️",
  keyboard: "⌨️",
  phone: "📱",
  iphone: "📱",
  telephone_receiver: "📞",
  email: "📧",
  mailbox: "📬",
  inbox_tray: "📥",
  outbox_tray: "📤",
  package: "📦",
  file_folder: "📁",
  open_file_folder: "📂",
  bookmark: "🔖",
  label: "🏷️",
  link: "🔗",
  lock: "🔒",
  unlock: "🔓",
  key: "🔑",
  shield: "🛡️",
  calendar: "📅",
  clock1: "🕐",
  clock2: "🕑",
  clock3: "🕒",
  hourglass: "⌛",
  hourglass_flowing_sand: "⏳",
  alarm_clock: "⏰",
  // Charts & data
  chart_with_upwards_trend: "📈",
  chart_with_downwards_trend: "📉",
  bar_chart: "📊",
  checkered_flag: "🏁",
  triangular_flag_on_post: "🚩",
  // Circles & squares
  red_circle: "🔴",
  large_orange_circle: "🟠",
  large_yellow_circle: "🟡",
  large_green_circle: "🟢",
  large_blue_circle: "🔵",
  purple_circle: "🟣",
  black_circle: "⚫",
  white_circle: "⚪",
  large_red_square: "🟥",
  large_orange_square: "🟧",
  large_yellow_square: "🟨",
  large_green_square: "🟩",
  large_blue_square: "🟦",
  large_purple_square: "🟪",
};

export function resolveEmoji(shortName: string): string {
  const key = shortName.replace(/^:|:$/g, "");
  return EMOJI_MAP[key] ?? shortName;
}

// Replaces all :shortcode: occurrences in a string with their emoji characters.
// Shortcodes not found in the map are left unchanged.
export function expandEmojiShortcodes(text: string): string {
  return text.replace(/:([a-zA-Z0-9_+\-]+):/g, (match, key) => EMOJI_MAP[key] ?? match);
}
